#!/usr/bin/env bash
set -euo pipefail

FRONTEND_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BACKEND_ROOT="$(dirname "$FRONTEND_ROOT")/interop-be-monorepo"
RUNTIME_ROOT="$FRONTEND_ROOT/.local-development"
LOG_ROOT="$RUNTIME_ROOT/logs"
SELECTION_FILE="$RUNTIME_ROOT/selection.env"

mkdir -p "$LOG_ROOT"

if [[ -f "$SELECTION_FILE" ]]; then
  # The file is generated by this script and contains only validated keys.
  source "$SELECTION_FILE"
fi
LOCAL_TENANT="${LOCAL_TENANT:-comune}"
LOCAL_USER="${LOCAL_USER:-admin}"

has_session() {
  tmux has-session -t "$1" 2>/dev/null
}

start_session() {
  local name="$1"
  local command="$2"
  local log_file="$LOG_ROOT/$name.log"
  if ! has_session "$name"; then
    : > "$log_file"
    tmux new-session -d -s "$name" \
      "bash -lc '$command 2>&1 | tee -a \"$log_file\"'"
  fi
}

wait_http() {
  local name="$1"
  local url="$2"
  local session="${3:-}"
  local attempts=0
  echo "Waiting for $name at $url"
  until curl --fail --silent --output /dev/null "$url"; do
    if [[ -n "$session" ]] && ! has_session "$session"; then
      echo "$name cannot start because $session exited unexpectedly." >&2
      echo "Last log lines from $LOG_ROOT/$session.log:" >&2
      tail -n 40 "$LOG_ROOT/$session.log" >&2 || true
      return 1
    fi
    attempts=$((attempts + 1))
    if (( attempts >= 180 )); then
      echo "Timed out waiting for $name at $url. See $LOG_ROOT/interop-backend.log" >&2
      return 1
    fi
    sleep 1
  done
  echo "$name is ready"
}

generate_token() {
  (cd "$BACKEND_ROOT" && pnpm local:token -- \
    --tenant "$LOCAL_TENANT" --user "$LOCAL_USER" \
    --output .local-development/frontend-token)
}

restart_frontend() {
  local mode="$1"
  has_session interop-frontend && tmux kill-session -t interop-frontend
  start_session interop-frontend \
    "cd \"$FRONTEND_ROOT\" && ./scripts/local-development/run-frontend.sh $mode"
  wait_http "frontend" "http://localhost:5173/ui/it" interop-frontend
  echo "Frontend ready in $mode mode on host port 3000 at path /ui/it/."
}

start() {
  echo "[1/7] Checking access to the host Docker daemon"
  docker info >/dev/null
  echo "[2/7] Starting host-port forwarding"
  start_session interop-port-forwards \
    "cd \"$FRONTEND_ROOT\" && ./scripts/local-development/forward-host-ports.sh"
  sleep 1
  if ! has_session interop-port-forwards; then
    echo "Port forwarding failed. See $LOG_ROOT/interop-port-forwards.log" >&2
    tail -n 40 "$LOG_ROOT/interop-port-forwards.log" >&2 || true
    return 1
  fi
  echo "[3/7] Starting Docker infrastructure and backend processes"
  start_session interop-backend \
    "cd \"$BACKEND_ROOT\" && pnpm local:start:frontend-full"
  wait_http "tenant process" "http://localhost:3500/status" interop-backend
  wait_http "catalog process" "http://localhost:3000/status" interop-backend
  wait_http "backend for frontend" \
    "http://localhost:3600/backend-for-frontend/0.0/status" interop-backend
  wait_http "in-app notification manager" "http://localhost:4200/status" \
    interop-backend
  echo "[4/7] Backend services are ready"
  echo "[5/7] Seeding tenants, events, and readmodels"
  (cd "$BACKEND_ROOT" && pnpm local:seed)
  echo "Seed completed successfully"
  echo "[6/7] Generating the local frontend token"
  generate_token
  echo "[7/7] Starting the frontend"
  restart_frontend local
}

stop() {
  for session in interop-frontend interop-backend interop-port-forwards; do
    has_session "$session" && tmux kill-session -t "$session"
  done
  (cd "$BACKEND_ROOT" && pnpm infra:stop)
  echo "Local full stack stopped; Docker volumes were preserved"
}

status() {
  for session in interop-port-forwards interop-backend interop-frontend; do
    if has_session "$session"; then echo "$session: running"; else echo "$session: stopped"; fi
  done
  echo
  echo "Backend application processes:"
  local pid_file="$BACKEND_ROOT/.local-development/frontend-full.pids"
  if [[ -s "$pid_file" ]]; then
    printf '%-66s %s\n' "SERVICE" "STATUS"
    while read -r service pid; do
      if kill -0 "$pid" 2>/dev/null; then
        printf '%-66s %s\n' "$service" "running"
      else
        printf '%-66s %s\n' "$service" "stopped"
      fi
    done < "$pid_file"
  else
    echo "No backend process registry available"
  fi
  echo
  echo "Docker infrastructure:"
  (cd "$BACKEND_ROOT" && docker compose -f docker/docker-compose.yml ps)
}

logs() {
  local service="${1:-backend}"
  local log_file="$LOG_ROOT/interop-$service.log"
  [[ -f "$log_file" ]] || { echo "No log available for $service" >&2; exit 1; }
  tail -n 200 -f "$log_file"
}

reset() {
  stop || true
  (cd "$BACKEND_ROOT" && pnpm infra:reset)
  rm -rf "$RUNTIME_ROOT"
  echo "Local full-stack data reset completed"
}

use_mode() {
  local mode="$1"
  if [[ "$mode" == "local" ]]; then generate_token; fi
  restart_frontend "$mode"
}

use_identity() {
  local tenant="$1"
  local user="$2"
  case "$tenant" in comune|provider|impresa|certificatore) ;; *) echo "Invalid tenant: $tenant" >&2; exit 1 ;; esac
  case "$user" in admin|api|security|reviewer|viewer) ;; *) echo "Invalid user: $user" >&2; exit 1 ;; esac
  LOCAL_TENANT="$tenant"
  LOCAL_USER="$user"
  printf 'LOCAL_TENANT=%q\nLOCAL_USER=%q\n' "$tenant" "$user" > "$SELECTION_FILE"
  generate_token
  restart_frontend local
}

case "${1:-}" in
  start) start ;;
  stop) stop ;;
  status) status ;;
  logs) logs "${2:-backend}" ;;
  reset) reset ;;
  use-local) use_mode local ;;
  use-dev) use_mode dev ;;
  identity) use_identity "${2:-}" "${3:-}" ;;
  *) echo "Usage: $0 {start|stop|status|logs [backend|frontend]|reset|use-local|use-dev|identity TENANT USER}" >&2; exit 1 ;;
esac
