export {
  EServiceTemplateInstancesTableRow as ConsumerEServiceTemplateInstancesTableRow,
  EServiceTemplateInstancesTableRowSkeleton as ConsumerEServiceTemplateInstancesTableRowSkeleton,
} from '@/components/shared/EserviceTemplate/EServiceTemplateInstancesTableRow'
