export const DEFAULT_LANG = 'it'
export const STORAGE_KEY_SESSION_TOKEN = 'token'

export const MOCK_TOKEN =
  'eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjE3YzExNzdmLWQ3ZGMtNDE4MS05ZjU0LTZmZDQxNmJmMjI5YiJ9.eyJpc3MiOiJkZXYuaW50ZXJvcC5wYWdvcGEuaXQiLCJ1c2VyLXJvbGVzIjoiYWRtaW4iLCJzZWxmY2FyZUlkIjoiODNlNmZjOWQtN2Y2MC00YTYyLThjZWMtNzg1NTI0YjZhMGE1Iiwib3JnYW5pemF0aW9uSWQiOiI2MmM2Y2Y3Zi1mMjc5LTQxYjEtYmQ3Ni0yNzk4MmU2NDkxZGYiLCJhdWQiOiJkZXYuaW50ZXJvcC5wYWdvcGEuaXQvdWkiLCJ1aWQiOiI0ZWE3MjJjMy1kZWZkLTQzNzItYTBjNC1iNDYxMzA3MmI2MzIiLCJuYmYiOjE2NjcyMDk3NzcsIm9yZ2FuaXphdGlvbiI6eyJpZCI6IjgzZTZmYzlkLTdmNjAtNGE2Mi04Y2VjLTc4NTUyNGI2YTBhNSIsIm5hbWUiOiJBZ2VuemlhIHBlciBMJ0l0YWxpYSBEaWdpdGFsZSIsInJvbGVzIjpbeyJwYXJ0eVJvbGUiOiJNQU5BR0VSIiwicm9sZSI6ImFkbWluIn1dLCJmaXNjYWxfY29kZSI6Ijk3NzM1MDIwNTg0In0sIm5hbWUiOiJBbmRyZWEiLCJleHAiOjE2NjcyOTYxNzcsImlhdCI6MTY2NzIwOTc3NywiZmFtaWx5X25hbWUiOiJCaWFuY2hpIiwianRpIjoiYzkwODU4ZTItZWJjMS00MGQ0LTliZDItNTU2YThlYTRhODYzIiwiZW1haWwiOiJhbmRyZWEuYmlhbmNoaUB0ZXN0Lml0In0.UidWIh4MgHV0Pm9VMcqO_AkgSmlsWxlMZZed81fUw3Q9q1TVV5d1SGNaaUGrfAfI5Hpxf8WeB7UiufXEFrtyw7y8iKF_0ZdhBCBZQLMhgJYkqJV3iJcd5AoERkaPYsPsYo1hwENdMLfTYQxqZhTzmVryD9qzAXw-dCOQZzVPXhvetzEqUHSnL5j9csOmUR2XM6a6vXqUhPxkuqwfrkNClRRo-kD8rGu9ZSIvC9HXABuAMeyWO2_Qb6zM_yBnMUu1QfEz7pyY4pvJhSznarR3TE7X3-M8oCmkzPIpru4gFERF1Uh1N-LBNZG_ovOD0hNR5uXc6cKWacam4TI5Bs06Kw'

export const LANGUAGES = {
  it: { it: 'Italiano', en: 'Inglese' },
  en: { it: 'Italian', en: 'English' },
}

export const pagoPaLink = {
  label: 'PagoPA S.p.A.',
  href: 'https://www.pagopa.it',
  ariaLabel: 'Vai al sito di PagoPA S.p.A.',
  title: 'Vai al sito di PagoPA S.p.A.',
}

export const documentationLink = 'https://docs.pagopa.it/interoperabilita-1/'
