export {
  EServiceTemplateInstancesTableRow as ProviderEServiceTemplateUsingTenantsTableRow,
  EServiceTemplateInstancesTableRowSkeleton as ProviderEServiceTemplateUsingTenantsTableRowSkeleton,
} from '@/components/shared/EserviceTemplate/EServiceTemplateInstancesTableRow'
